## The makeCacheMatrix function creates a "matrix" object that can cache its inverse. The cacheSolve function calculates the inverse of the matrix returned by the makeCacheMatrix function. If the inverse of a given matrix has already been calculated, then the cacheSolve function will retrieve the inverse matrix from the cache, instead of recalculating the inverse. If no inverse matrix is already cached, cacheSolve will cache the value of the inverse matrix after it has done the calculation. 

## The makeCacheMatrix function creates a list that will set the value of a matrix, get the value of a matrix, set the value of the inverse matrix, and get the value of the inverse matrix.

makeCacheMatrix <- function(x = matrix()){  	##This is a function that takes the argument x, which by default is a matrix
	m <- NULL				##Define the value of m as NULL.
	set <- function(y){			##The set function takes the argument y, and sets the value of the matrix.
		x <<- y				##x is assigned the value y if R cannot find an existing definition for x in                                                   parent environments.	
		m <<- NULL			##m is assigned the value NULL if R cannot find an existing definition for m                                                   in parent environments.
	}
	get <- function() x			        ##The get function returns x when called.
	setinverse <- function(inverse) m <<- inverse	##The setinverse function takes the argument "inverse", where inverse                                                           is assigned to m, if R cannot find an existing definition for m in                                                           parent environments.
	getinverse <- function() m	        	##The getinverse function returns m when called.
	list(set = set, get = get, 	        	##Creates a list that combines the four functions defined above.
	setinverse = setinverse, getinverse = getinverse)
}

##The cacheSolve function looks for a cached value for an inverse matrix, m. It returns the value if it exists, or calculates the inverse of matrix 'x' and stores that value in the cache (as m) if it doesn't already exist.

cacheSolve <- function(x, ...) { 		##This is a function that takes the formal argument x, and other arguments                                                     are passed to it from another function. 
        m <- x$getinverse()			##This line calls the getinverse function from the list generated by the                                                       makeCacheMatrix function, and sets m as this value (either NULL, or some                                                     value already in the cache).
		if(!is.null(m)) {		##If inverse matrix m already exists in the cache (i.e., is not NULL), then:
                message("getting cached inverse matrix")	##the message "getting cached inverse matrix" prints to the                                                                    console,
                return(m)		        ##...and the value m (the inverse matrix) is returned.
        }
        matrix <- x$get()			##If the value of m in the cache is NULL, this line calls the get function                                                     from the list generated by the makeCacheMatrix function, and stores the                                                      value x (your matrix) as "matrix".
        m <- solve(matrix, ...)			##The solve function will return the inverse of the matrix given by the first                                                   argument ("matrix"). m is set to this value.
        x$setinverse(m)				##This line calls the setinverse function from the makeCacheMatrix list,                                                       passing it the calculated value of m (the inverse matrix) to store in the                                                    cache.
        m					##Prints the inverse matrix, m.	
}
